### ISSUE TITLE
How get <my client name> and <my identity token> and <my cookie>

### ISSUE THREAD

**Issue by AliAkhtari78** [kazanture/YouPy#1]
Thanks for cloning PyTube,
I read this link [How to avoid HTTP error 429 (Too many requests) in python while using pytube library](https://mc.ai/how-to-avoid-http-error-429-too-many-requests-in-python-while-using-pytube-library/) but I couldn't find out how I can extract <my client name> and <my identity token> and <my cookie> you mentioned.
I did search network tap inside chrome dev tools, but I couldn't find these informations.

**Comment by emrebayramc** [comment]
Hi Ali,
goto your browser; open dev tools/network tab and goto youtube.
Then you will see Headers.

For example for Chrome;
1- you click top-right 3 dots to open chrome menu
2- Click "More Tools" then "Developer tools.
3- Click Network tab.
4- Open youtube on this browser tab.
5- You will see http requests flowing; click one of them. And you will see Header tab.

An example from web:
https://i.stack.imgur.com/1dolH.png

**Comment by emrebayramc** [comment]
@AliAkhtari78 
Response to your edited question:
if you do not send any requests; it will be empty.
you need to open youtube and click one of videos AFTER you opened the network tab.

**Comment by AliAkhtari78** [comment]
> @AliAkhtari78
> Response to your edited question:
> if you do not send any requests; it will be empty.
> you need to open youtube and click one of videos AFTER you opened the network tab.

yes, I found all the information I was looking for.

**Comment by AliAkhtari78** [comment]
Can I suggest you to use replace requests with selenium? I think it will solve all the issues.

**Comment by emrebayramc** [comment]
That makes sense; impersonating would be easier. I might do it when I have time(maybe next week). Thanks for the suggestion!
