### ISSUE TITLE
Got Error when try to download subtitle 

### ISSUE THREAD

**Issue by AliAkhtari78** [kazanture/YouPy#3]
I used this code to get subtitle of video, but I faced this error:
`  File "C:\Program Files (x86)\Python36-32\lib\site-packages\youpy-0.0.1-py3.6.egg\YouPy\captions.py", line 36, in generate_srt_captions
`
`  File "C:\Program Files (x86)\Python36-32\lib\site-packages\youpy-0.0.1-py3.6.egg\YouPy\captions.py", line 28, in xml_captions
`
`TypeError: get() missing 1 required positional argument: 'request_headers'`

**Comment by emrebayramc** [comment]
I think I have fixed this bug. Can you retry?

**Comment by AliAkhtari78** [comment]
thank you, it fixed now.
