### ISSUE TITLE
slow downloading

### ISSUE THREAD

**Issue by AliAkhtari78** [kazanture/YouPy#4]
when I run the script that I wrote with YouPy on my VPS, the maximum speed that the video is being to download is about 3 MB/s, my VPS download and upload speed is about 1GB/s and it takes a lot of time to download a video.
I check PyTube and found this issue in this link [Really slow downloading with CLI vs Interactive Prompt](https://github.com/nficano/pytube/issues/180) and it seems that the problem fixed when they update PyTube with multiprocessing file downloader.
I was wonder that can you do the same and Implement a multiprocessing downloader in YouPy?

**Comment by emrebayramc** [comment]
YouPy is a recent clone of PyTube and this issue is old so YouPy code should already contain this update.
But in any case; i will check the performance and try to improve it.

**Comment by AliAkhtari78** [comment]
Thank you,
But I deiced to stop using PyTube and use youtube-dl instead.
I suggest you to use youtube-dl instead too, it's fast and supports passing header and cookie too.
